---
title: Clínica Medicina e Saúde
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    cover_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    cover_image: 
- scope:
    path: ''
    type: slides
  values:
    image: 
description: Há 10 anos cuidado de você e sua família.
baseurl: "/medicinaesaude"
url: http://copatecnologia.com.br
permalink: "/:pretty/"
markdown: kramdown
plugins:
- jekyll-paginate
paginate: 8
paginate_path: "/blog/:num/"
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
