---
title: Clínica Medicina e Saúde
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  profissionais:
    title: Profissionais
    output: false
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:year/:month/:day/:title/"
    cover_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    icon_image: 
    title_color: 
    cover_image: 
- scope:
    path: ''
    type: profissionais
  values:
    image: 
- scope:
    path: ''
    type: slides
  values:
    image: 
    image-position: 
    text-position: 
    classes: 
description: Há 10 anos cuidado de você e sua família.
baseurl: "/medicinaesaude"
url: http://copatecnologia.com.br
permalink: "/:pretty/"
markdown: kramdown
plugins:
- jekyll-paginate
paginate: 8
paginate_path: "/blog/:num/"
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
- README.md
long-title: Clínica Medicina e Saúde
endereco:
- Praça da Independência, 11
- Gonzaga | CEP 11060-100 | Santos - SP | Brasil
telefones:
- numero: "+551332890001"
  rotulo: "(13) 3289-0001"
email: atendimento@clinicamedicinaesaude.com.br
social:
- label: Facebook
  link: http://facebook.com/medicinaesaude
  icone: facebook
- label: Linkedin
  link: http://linkedin.com/medicinaesaude
  icone: linkedin
- label: Twitter
  link: http://twitter.com/medicinaesaude
  icone: twitter
disqus-name: medicina-e-saude
blog:
  icon_image: 
  title_color: 
