---
title: Clínica Medicina e Saúde
timezone: America/Sao_Paulo
collections:
  profissionais:
    title: Profissionais
    output: false
  posts:
    title: Posts
    output: true
  slides:
    title: Slides
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:year/:month/:day/:title/"
    cover_image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    cover_image: 
- scope:
    path: ''
    type: profissionais
  values:
    image: 
- scope:
    path: ''
    type: slides
  values:
    image: 
description: Há 10 anos cuidado de você e sua família.
baseurl: "/medicinaesaude"
url: http://copatecnologia.com.br
permalink: "/:pretty/"
markdown: kramdown
plugins:
- jekyll-paginate
paginate: 8
paginate_path: "/blog/:num/"
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
- README.md
long-title: Clínica Medicina e Saúde
endereço: Praça da Independência, 11
localidade: Gonzaga | CEP 11060-100 | Santos - SP | Brasil
telefones:
- numero: "+551332890001"
  rotulo: "+55 (13) 3289-0001"
  icone: telefone
e-mail: atendimento@clinicamedicinaesaude.com.br
